# To make it easier to find descriptions and add exceptions
AllCops:
  TargetRubyVersion: 2.5
  DisabledByDefault: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/DuplicatedGem
# Checks for duplicate gem entries in Gemfile.
Bundler/DuplicatedGem:
  Enabled: true
  Include:
    - '**/Gemfile'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/OrderedGems
# Gems within groups in the Gemfile should be alphabetically sorted.
Bundler/OrderedGems:
  Enabled: true
  Include:
    - '**/Gemfile'

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/IndentHash
# To make reasonable use of whitespace
Layout/IndentHash:
  EnforcedStyle: 'consistent'

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/IndentArray
# To make reasonable use of whitespace
Layout/IndentArray:
  EnforcedStyle: 'consistent'

Layout/IndentationConsistency:
  Enabled: true

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/DotPosition
# So when reading code we know that given line has continuation
Layout/DotPosition:
  EnforcedStyle: 'leading'

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Lint/AmbiguousBlockAssociation
# It looks perfectly fine for asserting change
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/*_spec.rb'

Naming/ClassAndModuleCamelCase:
  Exclude:
    - '**/*_decorator.rb'

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Metrics/BlockLength
# It is common to have long blocks in routes, specs, matchers,
# factories and configuration files
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'
    - 'config/routes.rb'
    - 'config/routes/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/**/*_factory.rb'
    - 'spec/support/matchers/*.rb'
    - '**/*_spec.rb'

Metrics/LineLength:
  Enabled: 80

# https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Metrics/ModuleLength
# Large modules are totally fine in rspec
Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/AccessorMethodName
# It is common to expose `get_` like interface in wrappers
Naming/AccessorMethodName:
  Enabled: false
  Exclude:
    - 'app/wrappers/**/*.rb'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/VariableNumber
# More readable
Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Alias
# To keep it consistent. `alias` does not work for all cases (i.e. aliasing at runtime)
Style/Alias:
  EnforcedStyle: 'prefer_alias_method'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/BlockDelimiters
# It is common to use {} blocks for `expect`
Style/BlockDelimiters:
  Exclude:
    - '**/*_spec.rb'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FormatString
# The shortest syntax
Style/FormatString:
  EnforcedStyle: 'percent'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
# We do not care
Style/FrozenStringLiteralComment:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/GuardClause
# Sometimes using explicit condition is more readable
Style/GuardClause:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/GlobalVars
# FST: Disable for now. Should be refactored later
Style/GlobalVars:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MutableConstant
# Seriously this has never been a problem and it looks weird
Style/MutableConstant:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NumericLiterals
# It looks awkward for custom ids
Style/NumericLiterals:
  Exclude:
    - '**/*_spec.rb'
    - '**/*_factory.rb'

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/BeginBlock
Style/BeginBlock:
  Enabled: true

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/WordArray
Style/WordArray:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolArray
Style/SymbolArray:
  Enabled: false

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/UnknownEnv
Rails/UnknownEnv:
  Enabled: true
  Environments:
    - production
    - staging
    - development
    - test

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ClassAndModuleChildren
Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
